### PR TITLE
build: trigger pipelines

### PR DESCRIPTION
**Pull request by terovirtanen**
Refactor pipelines [OH-79](https://helsinkisolutionoffice.atlassian.net/browse/OH-79)

fixed black and isort issues too

[OH-79]: https://helsinkisolutionoffice.atlassian.net/browse/OH-79?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**PUISTOTALKOOT-API branch is deployed to platta: https://puistotalkoot-pr136.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**PUISTOTALKOOT-API branch is deployed to platta: https://puistotalkoot-pr136.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**PUISTOTALKOOT-API branch is deployed to platta: https://puistotalkoot-pr136.api.dev.hel.ninja** :rocket::rocket::rocket:

**Review by tuomas777 — APPROVED** [review]
LGTM 👍

**Pull request merged**
